paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      parameters:
        - name: limit
          in: query
          required: false
          description: Limite de productos a devolver
          schema:
            $type: String
        - name: page
          in: query
          required: false
          description: Número de página
          schema:
            $type: String
        - name: sort
          in: query
          required: false
          description: Orden ascendente o descendente
          schema:
            $type: String
        - name: query
          in: query
          required: false
          description: Categoría por la que filtrar
          schema:
            $type: String
      responses:
        "200":
          description: Los productos fueron devueltos satisfactoriamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  payload:
                    type: array
                    description: Array de productos
                    items:
                      $ref: '#components/schemas/Product'
                  totalDocs:
                    type: number
                    description: Cantidad de documentos
                  limit:
                    type: number
                    description: El limite de documentos por página
                  totalPages:
                    type: number
                    description: La cantidad total de páginas
                  page: 
                    type: number
                    description: Página actual
                  pagingCounter:
                    type: number
                    description: Contador del paginado
                  hasNextPage:
                    type: boolean
                    description: Indica si tiene próxima página
                  hasPrevPage:
                    type: boolean
                    description: Indica si tiene página anterior
                  prevPage:
                    oneOf:
                      - type: boolean
                      - type: null
                    description: Número de página anterior
                  nextPage:
                    oneOf:
                      - type: boolean
                      - type: null
                    description: Número de próxima página
    post:
      summary: Crea un producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/insertProduct'
      responses:
        "200":
          description: El producto fué creado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  payload:
                    type: object
                    description: Producto creado
                    $ref: '#components/schemas/Product'
        "401":
          description: Error de autenticación
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  error:
                    type: string
                    description: Descripción del error
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto solicitado
          schema:
            $type: String
      responses:
      "200":
        description: El producto fué devuelto satisfactoriamente
        content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  payload:
                    type: object
                    description: El producto solicitado
                    $ref: '#components/schemas/Product'
      "400":
        description: El ID no corresponde a ningún producto
        content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  error:
                    type: string
                    description: Descripción del error
    put:
      summary: Modifica un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto solicitado
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/insertProduct'
      responses:
        "200":
          description: El producto fue editado satisfactoriamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  payload:
                    type: object
                    description: El producto modificado
                    $ref: '#components/schemas/Product'
        "400":
          description: El ID no corresponde a ningún producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  error:
                    type: string
                    description: Descripción del error
        "401":
          description: Error de autenticación
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  error:
                    type: string
                    description: Descripción del error
    delete:
      summary: Elimina un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto solicitado
          schema:
            $type: String
      responses:
        "200":
          description: El producto fue eliminado satisfactoriamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  payload:
                    type: object
                    description: El producto eliminado
                    $ref: '#components/schemas/Product'
        "400":
          description: El ID no corresponde a ningún producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  error:
                    type: string
                    description: Descripción del error
        "401":
          description: Error de autenticación
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la solicitud
                  error:
                    type: string
                    description: Descripción del error
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código identificativo del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
        thumbnails:
          type: array
          items:
            type: string
          description: Fotos del producto
        owner:
          type: string
          description: Creador del producto
      example: 
        _id: ObjectId("64bd5318d08361c2a559823f")
        title: Nombre roducto
        description: Descripcion del producto
        code: FMV-959
        price: 1000
        status: true
        stock: 50
        category: Home
        thumbnails:
          - https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgD4KiXALCNRTxmBfVFoZ_3ltI88OHREHFiA&usqp=CAU
          - https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgD4KiXALCNRTxmBfVFoZ_3ltI88OHREHFiA&usqp=CAU
        owner: Admin
  requestBodies:
    insertProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código identificativo del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto
        stock:
          type: number
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
        thumbnails:
          type: array
          items:
            type: string
          description: Fotos del producto
        owner:
          type: string
          description: Creador del producto
    